apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: lh2bb7y4w-nodejs 
  janus-idp.io/tekton: lh2bb7y4w-nodejs
  backstage.io/kubernetes-id: lh2bb7y4w-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lh2bb7y4w-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml