apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lh2bb7y4w-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/lh2bb7y4w-nodejs-gitops